### PR TITLE
Our new exampe lesson

### PR DESCRIPTION
**Pull request by promark9**
Signed-off-by: promark9 <marek.plostica@gmail.com>

**High-Level Overview of this Curriculum Contribution**:

< Provide info here >

**Content Outline**:

**Does this PR fix an existing issue?**:

Fixes #

**Is This Ready to Review?**:

< Yes/No >

### CODE REVIEW

**Comment by Mierdin** [comment]
Hi @promark9 - this looks very much like it's not ready for review. The PR description contains none of the requested information, and the lesson metadata file is clearly still in its most skeleton form.

Please tell me a bit more about your intentions so we can either figure out a way to move this forward, or I'll have to close this PR.

**Comment by promark9** [comment]
> Hi @promark9 - this looks very much like it's not ready for review. The PR description contains none of the requested information, and the lesson metadata file is clearly still in its most skeleton form.
> 
> Please tell me a bit more about your intentions so we can either figure out a way to move this forward, or I'll have to close this PR.

Hello, I am just testing this tool but probably I have made some mistake. I will try to fix the problem. On the other hand I have some questions. Can I have type of image like IOS from Cisco? Or where can I find available and supported images? Thanks.

**Comment by Mierdin** [comment]
This is a curriculum for learning next-generation infrastructure engineering topics, and contributions must come in the form of content made with the intention of educating others towards this end. I suggest you read through https://docs.nrelabs.io/creating-contributing/getting-started to get a sense as to the intention of this project. The images supported by this curriculum are visible in the `images` directory.

This isn't simply a tool for emulating network devices like EVE-NG or GNS3. I suggest you work with one of those tools if your intention is to simulate a network topology for yourself or your team. If this is the case please let me know so I can close this PR.

**Comment by promark9** [comment]
> This is a curriculum for learning next-generation infrastructure engineering topics, and contributions must come in the form of content made with the intention of educating others towards this end. I suggest you read through https://docs.nrelabs.io/creating-contributing/getting-started to get a sense as to the intention of this project. The images supported by this curriculum are visible in the `images` directory.
> 
> This isn't simply a tool for emulating network devices like EVE-NG or GNS3. I suggest you work with one of those tools if your intention is to simulate a network topology for yourself or your team. If this is the case please let me know so I can close this PR.

Yes I got it. Thanks. But I need to do some tests of this tool because of school. I will read documentation more. Can I just trying to do some things without public on the real website of the tool? Just visible changes for me like I see in the video tutorial. Bot generated something and You saw that changes only by yourself.

**Comment by Mierdin** [comment]
In that case, I would recommend checking out the [selfmedicate](https://github.com/nre-learning/antidote-selfmedicate) tool. It's a self-contained version of the NRE Labs software that you can download and run on your own laptop. You will be on your own doing this, as it's no longer something I spend time supporting, but it's your only option. Using this repository to "test" is not appropriate.

**Pull request closed without merging**
