### PR TITLE
Removing tags from curriculum

### PR DESCRIPTION
**Pull request by Mierdin**
This PR removes all tags from lesson definitions to be compatible with Syringe changes introduced in https://github.com/nre-learning/syringe/pull/123.

To minimize the impact of this change, we have pushed a new tag for the existing images (i.e. `antidotelabs/vqfx:snap1`) at the exact same image ID, but to an image name that doesn't rely on tags for differentiation. So, instead of:

- `antidotelabs/vqfx:snap1`
- `antidotelabs/vqfx:snap2`
- `antidotelabs/vqfx:snap3`

We have:

- `antidotelabs/vqfx-snap1`
- `antidotelabs/vqfx-snap2`
- `antidotelabs/vqfx-snap3`

These images are cryptographically identical to their tagged counterpart, but without the tag, we can now inject the appropriate version at the Syringe level per the new behavior. Both `latest` and `v0.4.0` versions of these images have been identically pushed, so that both production and PTR/selfmedicate can get the images they need.

As a result, this PR changes the lesson files to point to the correct image. **NOTE** that this is a temporary measure to get the existing curriculum images compatible with the new format. Enhancements to these images to overcome the mac address issue requiring this snapshotting trick are still on the radar.

### CODE REVIEW

**Comment by b3115** [comment]
Well... Selfmedicate is still downloading vqfx:snap1, vqfx:snqp2 and vqfx:snap3.
Also this PR will make part of docs obsolete

**Comment by Mierdin** [comment]
@b3115 The docs will definitely get updated before the next release. In between releases, things should be expected to be pretty fluid. Ideally a docs PR should be joined at the hip with the change it describes, but I'm sure we can do better at that.

In addition, after the next release, selfmedicate will be updated accordingly. Note that selfmedicate only downloads those images in advance as a convenience function.

**Comment by b3115** [comment]
> Just set all to container-vqfx for now
This does not state how long it would be. As far as I understand, all lessons which had more than 1 vqfx will be failing. Maybe there should be some kind of warning in the beginning of these lessons

**Comment by b3115** [comment]
Have you tried to launch updated lessons? I've got timeout while loading lesson-12-jsnapy.

**Comment by Mierdin** [comment]
@b3115 Can you please move this conversation to our discord community or perhaps our forums? They're available at https://antidoteproject.readthedocs.io/en/latest/community.html

**Comment by b3115** [comment]
@Mierdin of course I can. The issue is my concerns are about the consequences of this particular PR and they are not referencing any earlier version. I've managed to load lesson-12 several times before and I would like to prevent from merging PR that may cause unexpected behavior (although I understand that currently this lesson doesn't work anyway). Forum thread might be ignored before merge.

**Pull request merged**
